name: Release
on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-beta.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Parse version and determine release type
        id: version_info
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          
          # Détermine si c'est une version beta ou latest
          if [[ $TAG_NAME == *"-beta"* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
            echo "release_type=Beta" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
            echo "release_type=Latest" >> $GITHUB_OUTPUT
          fi
          
          # Extrait la version de base (sans suffixe beta)
          BASE_VERSION=$(echo $TAG_NAME | sed 's/-beta.*//')
          echo "base_version=$BASE_VERSION" >> $GITHUB_OUTPUT

      - name: Get previous release tag
        id: previous_tag
        run: |
          # Pour les versions latest, trouve la précédente version latest
          # Pour les versions beta, trouve la précédente version (beta ou latest)
          if [[ "${{ steps.version_info.outputs.is_prerelease }}" == "false" ]]; then
            # Pour latest : cherche la dernière version non-beta
            PREVIOUS_TAG=$(git tag -l "v*.*.*" | grep -v beta | sort -V | tail -n 2 | head -n 1)
          else
            # Pour beta : cherche le dernier tag (peu importe le type)
            PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          fi
          
          if [ -z "$PREVIOUS_TAG" ]; then
            echo "previous_tag=" >> $GITHUB_OUTPUT
            echo "Aucun tag précédent trouvé"
          else
            echo "previous_tag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
            echo "Tag précédent: $PREVIOUS_TAG"
          fi

      - name: Generate changelog
        id: changelog
        run: |
          TAG_NAME="${{ steps.version_info.outputs.tag_name }}"
          PREVIOUS_TAG="${{ steps.previous_tag.outputs.previous_tag }}"
          IS_PRERELEASE="${{ steps.version_info.outputs.is_prerelease }}"
          
          # Initialise le changelog
          echo "# 🚀 Release $TAG_NAME" > changelog.md
          echo "" >> changelog.md
          
          # Ajoute des badges selon le type de release
          if [[ "$IS_PRERELEASE" == "true" ]]; then
            echo "![Beta](https://img.shields.io/badge/Release-Beta-orange) " >> changelog.md
          else
            echo "![Latest](https://img.shields.io/badge/Release-Latest-green) " >> changelog.md
          fi
          
          echo "" >> changelog.md
          
          # Génère le changelog basé sur les commits
          if [ ! -z "$PREVIOUS_TAG" ]; then
            echo "## 📋 What's Changed" >> changelog.md
            echo "" >> changelog.md
          
            # Utilise un fichier temporaire pour éviter les problèmes de sous-shell
            TEMP_FILE=$(mktemp)
          
            # Récupère les commits avec auteur, en excluant les commits de release
            git log --pretty=format:"%s|%an" --no-merges ${PREVIOUS_TAG}..${TAG_NAME} | \
              grep -v "^chore: release\|^release:\|^bump version\|^version bump" > "$TEMP_FILE"
          
            # Vérifie si on a des commits à traiter
            if [ -s "$TEMP_FILE" ]; then
              while IFS='|' read -r commit author; do
                # Évite les lignes vides
                if [ ! -z "$commit" ]; then
                  # Catégorise les commits selon leur préfixe
                  if [[ $commit == feat* ]] || [[ $commit == feature* ]]; then
                    echo "* ✨ $commit by @$author" >> changelog.md
                  elif [[ $commit == fix* ]]; then
                    echo "* 🐛 $commit by @$author" >> changelog.md
                  elif [[ $commit == docs* ]]; then
                    echo "* 📚 $commit by @$author" >> changelog.md
                  elif [[ $commit == style* ]]; then
                    echo "* 💄 $commit by @$author" >> changelog.md
                  elif [[ $commit == refactor* ]]; then
                    echo "* ♻️ $commit by @$author" >> changelog.md
                  elif [[ $commit == perf* ]]; then
                    echo "* ⚡ $commit by @$author" >> changelog.md
                  elif [[ $commit == test* ]]; then
                    echo "* 🧪 $commit by @$author" >> changelog.md
                  elif [[ $commit == chore* ]]; then
                    echo "* 🔧 $commit by @$author" >> changelog.md
                  elif [[ $commit == ci* ]]; then
                    echo "* 👷 $commit by @$author" >> changelog.md
                  elif [[ $commit == build* ]]; then
                    echo "* 🏗️ $commit by @$author" >> changelog.md
                  elif [[ $commit == revert* ]]; then
                    echo "* ⏪ $commit by @$author" >> changelog.md
                  else
                    echo "* 📝 $commit by @$author" >> changelog.md
                  fi
                fi
              done < "$TEMP_FILE"
            else
              echo "* 🔧 Version maintenance and updates" >> changelog.md
            fi
          
            # Nettoie le fichier temporaire
            rm "$TEMP_FILE"
          else
            echo "## 📋 What's Changed" >> changelog.md
            echo "" >> changelog.md
            echo "* 🎉 Initial release" >> changelog.md
          fi
          
          echo "" >> changelog.md
          
          # Ajoute des métriques (en excluant les commits de release)
          echo "## 📊 Release Stats" >> changelog.md
          echo "" >> changelog.md
          
          if [ ! -z "$PREVIOUS_TAG" ]; then
            # Compte les commits en excluant ceux de release
            COMMIT_COUNT=$(git log --oneline --no-merges ${PREVIOUS_TAG}..${TAG_NAME} | \
              grep -v "chore: release\|release:\|bump version\|version bump" | wc -l)
            echo "* 📦 **$COMMIT_COUNT commits** since $PREVIOUS_TAG" >> changelog.md
          fi
          
          TOTAL_COMMITS=$(git rev-list --count HEAD)
          echo "* 🔢 **$TOTAL_COMMITS total commits**" >> changelog.md
          
          # Compte les contributeurs uniques (en excluant les commits de release)
          TEMP_CONTRIBUTORS=$(mktemp)
          git log --pretty=format:"%an" --no-merges ${PREVIOUS_TAG:-$(git rev-list --max-parents=0 HEAD)}..${TAG_NAME} | \
            grep -v -f <(git log --pretty=format:"%an" --no-merges ${PREVIOUS_TAG:-$(git rev-list --max-parents=0 HEAD)}..${TAG_NAME} --grep="chore: release\|release:\|bump version\|version bump") | \
            sort -u > "$TEMP_CONTRIBUTORS" 2>/dev/null || \
            git shortlog -sn ${PREVIOUS_TAG:-$(git rev-list --max-parents=0 HEAD)}..${TAG_NAME} | \
            grep -v -E "(chore: release|release:|bump version|version bump)" | wc -l > "$TEMP_CONTRIBUTORS"
          
          CONTRIBUTORS=$(cat "$TEMP_CONTRIBUTORS" | wc -l)
          echo "* 👥 **$CONTRIBUTORS contributors** in this release" >> changelog.md
          rm "$TEMP_CONTRIBUTORS"
          
          echo "" >> changelog.md
          
          # Ajoute la liste des contributeurs (version améliorée)
          echo "## 👨‍💻 Contributors" >> changelog.md
          echo "" >> changelog.md
          
          # Récupère les contributeurs uniques avec leur nombre de commits
          git shortlog -sn ${PREVIOUS_TAG:-$(git rev-list --max-parents=0 HEAD)}..${TAG_NAME} | \
            while read count author; do
              # Vérifie si l'auteur a des commits non-release
              NON_RELEASE_COMMITS=$(git log --author="$author" --oneline --no-merges ${PREVIOUS_TAG:-$(git rev-list --max-parents=0 HEAD)}..${TAG_NAME} | \
                grep -v "chore: release\|release:\|bump version\|version bump" | wc -l)
          
              if [ "$NON_RELEASE_COMMITS" -gt 0 ]; then
                if [ "$NON_RELEASE_COMMITS" -eq 1 ]; then
                  echo "* 🙏 **$author** ($NON_RELEASE_COMMITS commit)" >> changelog.md
                else
                  echo "* 🙏 **$author** ($NON_RELEASE_COMMITS commits)" >> changelog.md
                fi
              fi
            done
          
          echo "" >> changelog.md
          
          # Ajoute un lien vers la comparaison complète
          if [ ! -z "$PREVIOUS_TAG" ]; then
            echo "## 🔗 Full Changelog" >> changelog.md
            echo "" >> changelog.md
            echo "**[View full diff](${{ github.server_url }}/${{ github.repository }}/compare/${PREVIOUS_TAG}...${TAG_NAME})**" >> changelog.md
            echo "" >> changelog.md
          fi
          
          echo "---" >> changelog.md
          echo "*Generated automatically by GitHub Actions* 🤖" >> changelog.md
          
          # Affiche le changelog généré pour debug
          echo "Changelog généré:"
          cat changelog.md
          
          # Sauvegarde le changelog pour le step suivant
          {
            echo 'CHANGELOG<<EOF'
            cat changelog.md
            echo EOF
          } >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version_info.outputs.tag_name }}
          name: ${{ steps.version_info.outputs.tag_name }}
          body_path: changelog.md
          prerelease: ${{ steps.version_info.outputs.is_prerelease }}
          make_latest: ${{ steps.version_info.outputs.is_prerelease == 'false' }}
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}